// <auto-generated />
namespace Group8.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Liam : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Liam));
        
        string IMigrationMetadata.Id
        {
            get { return "201709041214077_Liam"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
